/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lifengyi' at '16-11-21 下午3:05' with Gradle 2.14
 *
 * @author lifengyi, @date 16-11-21 下午3:05
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
